services:
  backend:
    image: mcr.microsoft.com/devcontainers/go:1-1.22-bookworm
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    # links:
    #   - frontend
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-networks

  frontend:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    ports:
      - 3000:3000
    networks:
      - app-networks

  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-networks
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  app-networks:
