paths:
  /scrap:
    GET:
      description: Scrap an url and return all the links
      parameters:
      - description: string
        in: query
        name: linkToScrap
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Scrapped links
          schema:
            $ref: '#/definitions/schemas.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/schemas.Response'
      tags:
      - scrap
