name: format backend

on:
  pull_request:
  push:

env:
  GO_VERSION: stable
  GOLANGCI_LINT_VERSION: v1.60

defaults:
  run:
    working-directory: ./backend


jobs:
  detect-backend-golang-modules:
    name: Detect Backend GoLang modules
    runs-on: self-hosted
    outputs:
      modules: ${{ steps.set-modules.outputs.modules }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - id: set-modules
        run: echo "modules=$(go list -m -json | jq -s '.' | jq -c '[.[].Dir]')" >> $GITHUB_OUTPUT

  run-backend-linter:
    name: Run Backend linter
    needs: detect-backend-golang-modules
    runs-on: self-hosted
    strategy:
      matrix:
        modules: ${{ fromJSON(needs.detect-backend-golang-modules.outputs.modules) }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: golangci-lint ${{ matrix.modules }}
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          working-directory: ${{ matrix.modules }}
          args: --enable-all --fix
