name: format frontend

on:
  pull_request:
  push:

defaults:
  run:
    working-directory: ./frontend

jobs:
  run-front-lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install Node.js dependencies
        run: npm ci

      - name: Install Node.js dependencies
        run: npm install -y eslint

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
