name: format frontend

on:
  pull_request:
  push:

defaults:
  run:
    working-directory: ./frontend

# Down scope as necessary via https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
permissions:
  checks: write
  contents: write

jobs:
  run-frontend-linter:
    name: Run Frontend linter
    runs-on: self-hosted

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node.js dependencies
        run: npm ci --include=dev

      - name: Verify ESLint installation
        run: npx eslint --version

      - name: Run ESLint
        run: npx eslint . --ext js,ts

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
          eslint_extensions: js,ts
          auto_fix: true
