# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches-ignore:
      - " ga-ignore-"
  pull_request:
    branches-ignore:
      - " ga-ignore-"

jobs:

  build:
    runs-on: [self-hosted, Linux]
    container:
      image: golang:1.20
    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: go build -v ./...

    - name: Golangci-lint
      uses: golangci/golangci-lint-action@v6.1.1


    - name: Test
      run: go test -v ./...
